//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Texton.rc
//
#define ID_ROI_WHOLE                    3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TEXTONTYPE                  129
#define IDD_THRES                       130
#define IDD_EDGEDET                     131
#define IDD_TASKS                       132
#define IDD_CONTOUR_OPTS                133
#define IDD_TMPL                        134
#define IDD_TEXTOUT                     138
#define IDD_HOUGH_OPTS                  139
#define IDD_ARCFIT                      141
#define IDD_FOURIER                     142
#define IDD_VOORHEES                    143
#define IDD_IFTW                        144
#define IDD_NOISEIMG                    145
#define IDD_STREAMLS                    146
#define IDD_STRM_ZOOM                   154
#define IDI_ZOOM_ICON                   158
#define IDI_ICACUK                      159
#define IDI_SOTON                       160
#define IDD_RESTORATION                 162
#define IDD_REST_ROI                    163
#define IDD_GL_RENDER                   165
#define IDD_ZOOMED_RESLICE              166
#define IDD_FINDVORTEX                  167
#define IDD_VOL_VIEW                    168
#define IDD_VORTEX_VTK                  171
#define IDI_VTK                         172
#define IDD_VTX_TRACKING                173
#define IDD_VTK_SAVE_ARROWS             174
#define IDD_VTX_MORE                    175
#define IDD_RESTOR_LOAD7D               176
#define IDD_FINDVORTEX_DICOM            177
#define IDC_THRES_LOWER                 1001
#define IDC_THRES_UPPER                 1002
#define IDC_THRES_SPINL                 1003
#define IDC_THRES_SPINU                 1004
#define ID_APPLY                        1005
#define IDC_CNY_STD                     1005
#define IDC_THRES_ANIMATE               1006
#define IDC_CNY_SPINSTD                 1006
#define IDC_ANIMATE_SHOW                1007
#define IDC_THRES_WIDTH                 1008
#define IDC_CNY_THL                     1008
#define IDC_CNY_THU                     1009
#define IDC_CNY_SPINL                   1010
#define IDC_CNY_SPINU                   1011
#define IDC_EDGE_SHOW                   1012
#define IDC_CANNY_GO                    1013
#define IDC_EDGE_RED                    1013
#define IDC_THRES_GO                    1014
#define IDC_CTR_DRAW                    1014
#define IDC_CONTDRW_GO                  1015
#define IDC_CTR_ERS                     1015
#define IDC_CTR_CLEAR                   1016
#define IDC_ORIGINAL_GO                 1016
#define IDC_CTR_IPRT                    1017
#define IDC_NOISEIMG_GO                 1017
#define IDC_ELLIPSE                     1018
#define IDC_CONTTMPL_GO                 1018
#define IDC_TMPL_START                  1019
#define IDC_HOUGH_GO                    1019
#define IDC_CIRCLE                      1019
#define IDC_TMPL_PROGRESS               1020
#define IDC_ARC_GO                      1020
#define IDC_PROGRESS1                   1021
#define IDC_FOURIER_GO                  1021
#define IDC_TMPL_START2                 1022
#define IDC_VOORHEES_GO                 1022
#define IDC_IFTW_GO                     1023
#define IDC_STREAMLNS                   1024
#define IDC_TMPL_DRAWFIT                1025
#define IDC_RESTORATION_GO              1025
#define IDC_DRAW_ERROR                  1026
#define IDC_VORTEX_GO                   1026
#define IDC_TMPL_DRAWORI                1027
#define IDC_TMPL_POWELL                 1028
#define IDC_TMPL_SIMPLEX                1029
#define IDC_TPL_ANGLE                   1030
#define IDC_TPL_WP                      1031
#define IDC_TPL_LW                      1032
#define IDC_TPL_LH                      1033
#define IDC_TPL_W                       1034
#define IDC_TPL_G                       1035
#define IDC_TPL_CX                      1036
#define IDC_TPL_CY                      1037
#define IDC_TPL_ANGMAG                  1038
#define IDC_TPL_WPMAG                   1039
#define IDC_TPL_LWMAG                   1040
#define IDC_TPL_LHMAG                   1041
#define IDC_TPL_WMAG                    1042
#define IDC_TPL_GMAG                    1043
#define IDC_TMPL_FINAL                  1044
#define IDC_TPL_INTWGTH                 1045
#define IDC_TPL_WPWGTH                  1046
#define IDC_TPL_TRAINWP                 1047
#define IDC_TPL_TRAINLW                 1048
#define IDC_TPL_TRAINLH                 1049
#define IDC_TPL_LWWGTH                  1050
#define IDC_TMPL_DRAWINIT               1051
#define IDC_TPL_LHWGTH                  1052
#define IDC_TMPL_POSFIX                 1053
#define IDC_TMPL_SAVE                   1054
#define IDC_TPL_TRAINW                  1055
#define IDC_TPL_TRAING                  1056
#define IDC_TPL_MHWGTH                  1057
#define IDC_TMPL_TMPFIX                 1058
#define IDC_TPL_TRAINANG                1059
#define IDC_TPL_MAXERR                  1060
#define IDC_BUTTON1                     1061
#define IDC_TMPLDSTC                    1062
#define IDC_ARCFIT_REDRAW               1062
#define IDC_SHOW_U                      1062
#define IDC_RESTOR_2DVIS_RESTORED       1062
#define IDC_X_PLUS                      1062
#define IDC_LMS_DISTS                   1062
#define IDC_TPL_MAXERR2                 1063
#define IDC_ARCFIT_CANNY                1063
#define IDC_RESTOR_2DVIS_DATA           1063
#define IDC_Y_PLUS                      1063
#define IDC_TPL_MAXERR3                 1064
#define IDC_ARCFIT_BINS                 1064
#define IDC_RESTOR_3DVIS_RESTORED       1064
#define IDC_S_MINUS                     1064
#define IDC_ARCFIT_ORIGREEN             1065
#define IDC_SHOW_NSE                    1065
#define IDC_RESTOR_3DVIS_DATA           1065
#define IDC_X_MINUS                     1065
#define IDC_ARCFIT_ORYTOCANNY           1066
#define IDC_SHOW_V                      1066
#define IDC_RESTOR_2DVIS_NOISY          1066
#define IDC_Y_MINUS                     1066
#define IDC_RESTOR_3DVIS_DATA2          1066
#define IDC_ARCFIT_CLAIMS               1067
#define IDC_SHOW_W                      1067
#define IDC_RESTOR_3DVIS_NOISY          1067
#define IDC_DRAW_THRES                  1068
#define IDC_ARCFIT_CLAIMARCS            1068
#define IDC_SHOW_TXT                    1068
#define IDC_RESTOR_3DVIS_NOISYDATA      1068
#define IDC_TEXTEDIT                    1069
#define ID_HOUGH_APPLY                  1070
#define IDC_HOUGH_MIN                   1071
#define IDC_HOUGH_MAX                   1072
#define IDC_HOUGH_CIRCLES               1073
#define IDC_HOUGH_ELLIPSES              1074
#define IDC_HOUGH_SAVE                  1075
#define IDC_EDGE_SAVE                   1076
#define IDC_ARC_MIN_PNTS                1077
#define IDC_ARC_MAX_ERROR               1078
#define IDC_ARCFIT_TEXT                 1079
#define IDC_ARCFIT_IMGSIZE              1080
#define IDC_ARC_MAX_PNTS                1081
#define IDC_FFT_FFT                     1082
#define IDC_FFT_ROTATE                  1083
#define IDC_FFT_COMBINE                 1084
#define IDC_FFT_DEGREES                 1085
#define IDC_FFT_CANNY                   1086
#define IDC_FFT_FFTROT                  1087
#define IDC_FFT_CANNYCOPY               1088
#define IDC_FFT_ROTATE_STATIC1          1089
#define IDC_FFT_ROTATE_STATIC2          1090
#define IDC_FFT_INVERSE                 1091
#define IDC_FFT_ROTINVERSE              1092
#define IDC_FFT_COMINV                  1093
#define IDC_LOG                         1094
#define IDC_LOG_THRES                   1095
#define IDC_SHOW_ORI                    1096
#define IDC_SAVE                        1097
#define IDC_THRES_AT                    1098
#define IDC_PEAKS                       1098
#define IDC_AT_THRES                    1099
#define IDC_STATIC_IFTW_DOTS            1099
#define IDC_GAUSS_BLUR                  1100
#define IDC_IFTW_WATERSHED_GO           1100
#define IDC_BLUR_SIGMA                  1101
#define IDC_IFTW_SHOW_PEAKS             1101
#define IDC_IFTW_ORIGINAL               1102
#define IDC_IFTW_SHOW_W                 1103
#define IDC_IFTW_COSTS                  1104
#define IDC_NOISE_GO                    1104
#define IDC_IFTW_SHOW_COSTS             1105
#define IDC_NOISE_SEED                  1105
#define IDC_NOISE_MEAN                  1106
#define IDC_NOISE_STD                   1107
#define IDC_STRM_VORTEX                 1109
#define IDC_STRM_LOAD                   1110
#define IDC_STRM_NOISE                  1111
#define IDC_STRM_ALPHA                  1112
#define IDC_STRM_LAPLW                  1113
#define IDC_STRM_OPT_ITS                1114
#define IDC_STRM_OPT_STP                1115
#define IDC_STRM_ITS_NEXT               1116
#define IDC_STRM_ITS                    1117
#define IDC_STRM_GO                     1118
#define IDC_STR_NOISE_S                 1119
#define IDC_STR_NOISE_M                 1120
#define IDC_STR_NOISE_V                 1121
#define IDC_STR_NOISE_B                 1122
#define IDC_SHOW_MR                     1123
#define IDC_RESTOR_3DNOISE_S2           1123
#define IDC_STRM_RES_SAVE               1124
#define IDC_RESTOR_3DNOISE_M2           1124
#define IDC_STRM_DELTA                  1125
#define IDC_RESTOR_3DNOISE_V2           1125
#define IDC_STRM_TXT_BLUR               1126
#define IDC_RESTOR_3DNOISE_B2           1126
#define IDC_STRM_VTX_RANGE              1127
#define IDC_RESTOR_3DNOISE_B3           1127
#define IDC_STRM_TXT_MAGN               1128
#define IDC_STRM_FLIP_U                 1129
#define IDC_STRM_FLIP_V                 1130
#define IDC_STRM_FLIP_W                 1131
#define IDC_STRM_TXT_COLOUR             1132
#define IDC_STRM_ZOOM                   1133
#define IDC_STRM_MAG_MULT               1134
#define IDC_STRM_INT_MULT               1135
#define IDC_ZOOM_COORDS                 1136
#define IDC_STRM_LOAD3D                 1136
#define IDC_STRM_NOISE_GRID             1137
#define IDC_STRM_VIEW_LAPLACIAN         1138
#define IDC_RESTOR_2DGO                 1139
#define IDC_STRM_TXT_SEED               1139
#define IDC_RESTOR_2DVORTEX             1140
#define IDC_RESTOR_2DLOAD               1141
#define IDC_RESTOR_2DVRANGE             1142
#define IDC_RESTOR_3DVORTEX             1143
#define IDC_RESTOR_3DLOAD               1144
#define IDC_RESTOR_3DVRANGE             1145
#define IDC_RESTOR_3DGO                 1146
#define IDC_RESTOR_3DLOAD2              1147
#define IDC_RESTOR_3D_RESTORED_SLICE    1148
#define IDC_RESTOR_2D_NOISE_GO          1149
#define IDC_RESTOR_3D_HEART_LOAD        1149
#define IDC_RESTOR_3D_RESTORED_RANGE    1150
#define IDC_RESTOR_3D_NOISE_GO          1151
#define IDC_RESTOR_2DNOISE_S            1152
#define IDC_RESTOR_7DLOAD               1152
#define IDC_RESTOR_2DNOISE_M            1153
#define IDC_RESTOR_2DNOISE_V            1154
#define IDC_RESTOR_2DNOISE_B            1155
#define IDC_2DRESTOR_LAMBDA             1156
#define IDC_2DRESTOR_DELTAT             1157
#define IDC_2DRESTOR_ITERATIONS         1158
#define IDC_2DRESTOR_OMEGA              1159
#define IDC_2DRESTOR_MINLAMBDA_DIFF     1160
#define IDC_RESTOR_ITS                  1161
#define IDC_RESTOR_LAMBDA               1162
#define IDC_RESTOR2D_LAMBDA_FIX         1163
#define IDC_RESTOR_2D_ROI               1164
#define IDC_RESTOR_ROI_TEXT             1165
#define IDC_ROI_COORDS                  1166
#define IDC_RESTOR_UTVE                 1166
#define IDC_RESTOR_CTVE                 1167
#define IDC_STR_ZOOM_TEXT               1168
#define IDC_3DRESTOR_LAMBDA             1168
#define IDC_3DRESTOR_DELTAT             1169
#define IDC_3DRESTOR_ITERATIONS         1170
#define IDC_EDITTEXT                    1171
#define IDC_3DRESTOR_SIGMA              1171
#define IDC_3DRESTOR_MINLAMBDA_DIFF     1172
#define IDC_RESTOR3D_LAMBDA_FIX         1173
#define IDC_RESTOR_3D_ROI               1174
#define IDC_3DRESTOR_ROI_TEXT           1175
#define IDC_RESTOR_3DNOISE_SLICES       1176
#define IDC_3DRESTOR_ITS                1177
#define IDC_3DRESTOR_LAMBDAD            1178
#define IDC_3DRESTOR_UTVE               1179
#define IDC_3DRESTOR_CTVE               1180
#define IDC_3DRESTOR_RMS                1181
#define IDC_ALPHADYN                    1182
#define IDC_STATIC_ALPHA                1183
#define IDC_2D_ERROR                    1184
#define IDC_STRM_ZOOM_SIZE              1185
#define IDC_2D_ERROR2                   1186
#define IDC_2D_ERROR3                   1187
#define IDC_3D_ERROR_COMP               1188
#define IDC_RESTOR3D_IMGSIZES           1189
#define IDC_3D_ERROR_3DCOMP             1190
#define IDC_RESTOR3D_RESLICE_XVAL       1191
#define IDC_RESTOR3D_RESLICE_X          1192
#define IDC_RESTOR3D_RESLICE_YVAL       1193
#define IDC_RESTOR3D_RESLICE_Y          1194
#define IDC_RESTOR3D_RESLICE_SLICE      1195
#define IDC_RENDER                      1196
#define IDC_RESTOR3D_ZOOM_SCALE         1197
#define IDC_ROI_TX                      1197
#define IDC_3D_ERROR_3DCOMP_MEM         1198
#define IDC_ROI_TY                      1198
#define IDC_ROI_BX                      1199
#define IDC_ROI_BY                      1200
#define IDC_ROI_BOOL                    1201
#define IDC_ZOOMED_SLICE_IMGSIZE        1202
#define IDC_ZOOMED_S                    1203
#define IDC_ZOOMED_X                    1204
#define IDC_ZOOMED_Y                    1205
#define IDC_ZOOM_ZCOORD                 1206
#define IDC_ZOOM_XCOORD                 1207
#define IDC_STRM_S                      1207
#define IDC_ZOOM_YCOORD                 1208
#define IDC_STRM_X                      1208
#define IDC_ZOOMED_3D                   1209
#define IDC_STRM_Y                      1209
#define IDC_STRM_SCOORD                 1210
#define IDC_STRM_XCOORD                 1211
#define IDC_VORTEX_3DLOAD               1211
#define IDC_STRM_YCOORD                 1212
#define IDC_VORTEX_DATALOAD             1212
#define IDC_STATIC_IMAGEINFO            1213
#define IDC_VORTEX_VELMAGN              1214
#define IDC_VORTEX_VELMAGN_VIEW         1215
#define IDC_S_SEL                       1215
#define IDC_X_SEL                       1216
#define IDC_VORTEX_VELMAGN_THRES        1216
#define IDC_Y_SEL                       1217
#define IDC_VORTEX_VELMAGN_VIEW_THRES   1217
#define IDC_S_PLUS                      1218
#define IDC_VORTEX_GRADMAT_GO           1218
#define IDC_STATIC_IMGINFO              1219
#define IDC_VORTEX_VORTEX_GRADMAT_VIEW  1219
#define IDC_FINDVORTEX_VELMAGN_THRES    1220
#define IDC_STATIC_VOXVAL               1220
#define IDC_STATIC_VOLTITLE             1221
#define IDC_VOLVIEW_SELECT              1222
#define IDC_STRM_IMGSIZES               1223
#define IDC_VOLVIEW_MULTIPLIER          1223
#define IDC_VORTEX_WN_GO                1223
#define IDC_VORTEX_WN_VIEW              1224
#define IDC_VORTEX_CIRCLERAD            1225
#define IDC_VORTEX_ATPOSITION           1226
#define IDC_VORTEX_EIG1                 1227
#define IDC_VORTEX_EIG2                 1228
#define IDC_VORTEX_EIG3                 1229
#define IDC_VORTEX_DUDX                 1230
#define IDC_VORTEX_DUDX2                1231
#define IDC_VORTEX_DUDX3                1232
#define IDC_VORTEX_DUDX4                1233
#define IDC_VORTEX_DUDX5                1234
#define IDC_VORTEX_DUDX6                1235
#define IDC_VORTEX_DUDX7                1236
#define IDC_VORTEX_DUDX8                1237
#define IDC_VORTEX_DUDX9                1238
#define IDC_VORTEX_3DVORTEX             1239
#define IDC_VORTEX_3DVRANGE             1240
#define IDC_VORTEX_3DNOISE_SLICES       1241
#define IDC_VOLVIEW_SAVE                1242
#define IDC_VORTEX_CINDEX_TOL           1242
#define IDC_VORTEX_VIEW_REAL            1243
#define IDC_VORTEX_VIEW_IMAG            1244
#define IDC_RESTOR_FIND_VORTEX          1244
#define IDC_VORTEX_FLIPU                1245
#define IDC_VORTEX_FLIPV                1246
#define IDC_VORTEX_FLIPW                1247
#define IDC_VORTEX_FLIPPEDU             1248
#define IDC_VORTEX_FLIPPEDv             1249
#define IDC_VORTEX_FLIPPEDw             1250
#define IDC_VORTEX_WN_SLICE             1251
#define IDC_VORTEX_VORTICITY_GO         1252
#define IDC_VORTEX_VIEW_TOLERANCE       1253
#define IDC_VORTEX_VORTICITY_VIEW       1254
#define IDC_VORTEX_VORTICITY_X          1255
#define IDC_VORTEX_VORTICITY_Y          1256
#define IDC_VORTEX_VORTICITY_Z          1257
#define IDC_VORTEX_LAMBDA_VIEW_NEGATIVE 1258
#define IDC_VORTEX_STRM_VORTICITY       1259
#define IDC_VORTEX_VORTICITY_THRES      1260
#define IDC_VORTEX_STRM_VIEW            1261
#define IDC_VORTEX_STRM_MAGN            1262
#define IDC_VORTEX_VTK_GO               1262
#define IDC_VORTEX_MAGN_THRES           1263
#define IDC_VORTEX_STRM_EIGIMAG         1264
#define IDC_STRM_VTK_STREAMER           1264
#define IDC_VORTEX_STRM_EIGIMAG_THRES   1265
#define IDC_STRM_VTK_LINEMAP            1265
#define IDC_VORTEX_VTK_VIEW             1266
#define IDC_STRM_VTK_STREAMER_LIC       1266
#define IDC_VORTEX_STRM_POSITION        1267
#define IDC_VORTEX_STRM_EIGIMAG_POS_X   1268
#define IDC_VORTEX_STRM_EIGIMAG_POS_Y   1269
#define IDC_VORTEX_STRM_EIGIMAG_POS_Z   1270
#define IDC_STRM_VORTICITY_VALID        1271
#define IDC_VORTEX_STRM_MAGN_VALID      1272
#define IDC_VORTEX_STRM_EIGIMAG_VALID   1273
#define IDC_VORTEX_VTK_ARROWS           1274
#define IDC_VORTEX_LAMBDA_GO            1275
#define IDC_STRM_VTK_ARROWS3D           1275
#define IDC_VORTEX_LAMBDA_VIEW          1276
#define IDC_VORTEX_LAMBDA_ATPOSITION    1277
#define IDC_VORTEX_LAMBDA_EIG1          1278
#define IDC_VORTEX_LAMBDA_EIG2          1279
#define IDC_VORTEX_LAMBDA_EIG3          1280
#define IDC_VORTEX_LAMBDA_DUDX          1281
#define IDC_VORTEX_LAMBDA_DVDX          1282
#define IDC_VORTEX_LAMBDA_DWDX          1283
#define IDC_VORTEX_LAMBDA_DUDY          1284
#define IDC_VORTEX_LAMBDA_DWDZ          1285
#define IDC_VORTEX_LAMBDA_DVDY          1286
#define IDC_VORTEX_LAMBDA_DVDZ          1287
#define IDC_VORTEX_LAMBDA_DWDY          1288
#define IDC_VORTEX_LAMBDA_DUDZ          1289
#define IDC_VORTEX_STRM_LAMBDA          1290
#define IDC_VORTEX_STRM_WN              1291
#define IDC_VORTEX_STRM_LAMBDA_VALID    1292
#define IDC_VORTEX_STRM_VIEW_MASK       1293
#define IDC_STRM_VORTICITY_VECTOR       1294
#define IDC_FINDVORTEX_FLOWVIS_TRACKING 1295
#define IDC_VORTEX_3DNOISE_PIXELS       1295
#define IDC_TRACKING_LOADED             1296
#define IDC_TRACKING_TRACKED            1297
#define IDC_TRACKING_SPACERAD           1298
#define IDC_TRACKING_TIMERAD            1299
#define IDC_RESTOR_CCFD_ROI_PRESET      1301
#define IDC_RESTOR_ZERO_SKIP            1302
#define IDC_CONDENSATION_GO             1303
#define IDC_DENSE_MEAN                  1304
#define IDC_DENSE_SCALING               1305
#define IDC_DENSE_SIGMA                 1306
#define IDC_STATIC_DENSE_X              1307
#define IDC_STATIC_DENSE_Y              1308
#define IDC_FINDVORTEX_TRACKING         1309
#define IDC_VORTEX_VTK_SAVE_ARROWS      1310
#define IDC_FINDVORTEX_DICOM            1311
#define IDC_SAVE_VTK_ARROWS_IMGSIZE     1312
#define IDC_SAVE_VTK_ARROWS_ZCOORD      1317
#define IDC_SAVE_VTK_ARROWS_XCOORD      1318
#define IDC_SAVE_VTK_ARROWS_YCOORD      1319
#define IDC_SAVE_VTK_ARROWS_3D          1320
#define IDC_SAVE_VTK_ARROWS_S           1321
#define IDC_SAVE_VTK_ARROWS_X           1322
#define IDC_SAVE_VTK_ARROWS_Y           1323
#define IDC_SAVE_VTK_ARROWS_HCFD        1324
#define IDC_LMS_USE                     1324
#define IDC_LMS_SIZE                    1325
#define IDC_LMS_POS                     1327
#define IDC_LMS_VTK_POSITIONS           1328
#define IDC_LMS_VTK_DISTANCES           1329
#define IDC_VORTEX_SAVEDATA             1330
#define IDC_MORE_VTX                    1331
#define IDC_VORTEX_SAVEDATA3D           1332
#define IDC_IFTW_ROOT_TITLE_STATIC      1334
#define IDC_IFTW_ROOT_VALUE_STATIC      1335
#define IDC_IFTW_INTERACT               1336
#define IDC_IFTW_PROPAG                 1337
#define IDC_IFTW_MACCOST                1338
#define IDC_IFTW_MAXCIRRAD              1339
#define IDC_IFTW_CHECK_ROOTS            1340
#define IDC_IFTW_MAXITS                 1341
#define IDC_IFTW_SAVEMATLAB             1342
#define IDC_REGIONS_GO                  1343
#define IDC_REGION_SAVE_ARROWS          1344
#define IDC_REGIONS_SAVE_POINTS         1345
#define IDC_REGIONS_COMPRESSION         1346
#define IDC_REGIONS_CLUSTERS            1347
#define IDC_REGIONS_COMPRESSION_SELECT  1348
#define IDC_REGIONS_CLUSTERS_SELECT     1349
#define IDC_REGION_VIEW_CLUSTERS        1350
#define IDC_VORTEX_REGION_CRPOINTS      1351
#define IDC_REGIONS_SAVE_VELOCITY       1351
#define IDC_VOLVIEW_MINMAX              1352
#define IDC_REGION_SAVE_CLUSTERS        1352
#define IDC_REGIONS_LOAD_CLUSTERS       1353
#define IDC_VTXMORE_VIEWBIN             1354
#define IDC_RESTOR_7D_TIME              1355
#define IDC_REGIONS_SAVE_LMSDIST        1355
#define IDC_STRM_SEED1                  1356
#define IDC_STRM_SEED2                  1357
#define IDC_VTX_MORE_LOADED             1357
#define IDC_STRM_SEED3                  1358
#define IDC_REGIONS_SAVE_MATLAB_VEL     1358
#define IDC_REGIONS_SAVE_MATLAB_ORIGINAL 1359
#define IDC_REGIONS_LOAD_STRM           1360
#define IDC_REGION_SAVE_SEEDS           1361
#define IDC_REGIONS_STREAMLINES         1362
#define IDC_REGIONS_STRM_STATIC         1363
#define IDC_REGIONS_XCORR_STATIC        1364
#define IDC_REGION_RENDER_ALL           1365
#define IDC_REGION_RENDER_XCORR         1366
#define IDC_REGIONS_XCORR_GO            1367
#define IDC_REGIONS_XCORR_STATIC2       1368
#define IDC_REGIONS_XLENGTH_THRES       1369
#define IDC_REGIONS_SIZE_THRES          1370
#define IDC_REGIONS_MINCURL             1371
#define IDC_REGION_RENDER_CURL          1372
#define IDC_REGIONS_MINMAGN             1373
#define IDC_REGION_RENDER_MAG           1374
#define IDC_REGION_RENDER_MAGN_CURL     1375
#define IDC_REGIONS_MATLAB_SAVE_XCORR   1376
#define IDC_REGION_SAVE_VTK_XCORR_VEL   1377
#define IDC_REGIONS_CLUSTER_INFORMATION 1378
#define IDC_REGIONS_INFO_RESULT         1379
#define IDC_REGIONS_INFO_RANGES         1380
#define IDC_REGIONS_INFORMATION_BATCH_GO 1381
#define IDC_DICOM_SAVE_GO               1382
#define IDC_VTX_SEED_STRM               1383
#define ID_FILE_IMPORTPGM               32771
#define ID_BUTTON_ED                    32773
#define ID_BUTTON_OR                    32774
#define ID_BUTTON_TE                    32775
#define ID_BUTTON_THRES                 32776
#define ID_VIEW_TASKS                   32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1384
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
